### PR TITLE
env_logger version 0.10.0

### PR DESCRIPTION
**Pull request by Pavel-Durov**
Upgraded env_logger version to 0.10.0 as an attempt to fix
https://rustsec.org/advisories/RUSTSEC-2021-0145

### CODE REVIEW

**Comment by vext01** [comment]
Did it fix the audit?

**Comment by Pavel-Durov** [comment]
CI runs somekind of python script:
```python
python3 -u audit.py
```
https://ci.soft-dev.org/#/builders/4/builds/205/steps/4/logs/stdio

**Comment by vext01** [comment]
> CI runs somekind of python script

That's not the CI script for your repo. It's basically a glorified cron job run by buildbot.

You can run the audit for your repo with (I think):
```
cargo install cargo-audit
cargo audit
```

**Comment by Pavel-Durov** [comment]
Ok, got it!
locally seems to be OK:
```
$ cargo audit
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 526 security advisories (from /home/kimchi/.cargo/advisory-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (79 crate dependencies)
```

**Comment by Pavel-Durov** [comment]
although locally I get audit passing for the main branch as well...

**Comment by vext01** [comment]
odd.

I don't think this can do any harm, so let's merge it.

bors r+

**Pull request merged**
